name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. VM에서 repository를 내려받음
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. VM에 JDK를 셋팅
      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17' # 사용하는 버전으로 수전
          distribution: 'temurin' # 배포판 선택
          
      # 3. Gradle Caching 셋팅
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      
      # 4. Gradle Build
      - name: Build with Gradle
        run: ./gradlew build
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
  
      - name: Build and push Docker image
        run: |
          docker build -t isayaksh/about:latest .
          docker push isayaksh/about:latest
